services:
  web:
    container_name: rihal-website-web
    build:
      context: ./web
      target: base
    working_dir: /app
    entrypoint: ["/bin/sh", "/app/entrypoint.sh"]
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app:rw,cached
      - /app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rihal-website

networks:
  rihal-website:
